name: publish dev image docker
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
  workflow_dispatch:
  
jobs:
  build:
    if: github.repository_owner == 'rz65hege'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Update Version number
      - name: Update version file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: recipes/version.py
          contents: |
            VERSION_NUMBER = 'develop'
            BUILD_REF = '${{ github.sha }}'
          write-mode: overwrite
      # Build Vue frontend
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Clear Cache
        working-directory: ./vue
        run: yarn cache clean --all
      - name: Install dependencies
        working-directory: ./vue
        run: yarn install
      - name: Build dependencies
        working-directory: ./vue
        run: yarn build
      # Build container
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.13
        with:
          name: ${{ secrets.DOCKER_REPONAME }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
  deploy_heroku:
    name: Deploy on Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        working-directory: frontend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
